/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nurfaamk Cyform (https://sketchfab.com/nurhudaiffah)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bloom-light-7c63fddf1e874a3196d6ceb3386b69d1
title: BLOOM LIGHT
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gltf/bloomlight.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      {/* <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -9.9, 0]} scale={404.65}>
            <mesh geometry={nodes.pPlane1_lambert2_0.geometry} material={materials.lambert2} />
          </group>
          <group position={[-40.56, 66.97, 0]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube1_lambert3_0.geometry} material={nodes.pCube1_lambert3_0.material} />
          </group>
          <group position={[0, 66.97, 105.24]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube2_lambert3_0.geometry} material={nodes.pCube2_lambert3_0.material} />
          </group>
          <group position={[-73.94, 66.97, 105.24]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube3_lambert3_0.geometry} material={nodes.pCube3_lambert3_0.material} />
          </group>
          <group position={[-39.2, 66.97, 105.24]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube4_lambert3_0.geometry} material={nodes.pCube4_lambert3_0.material} />
          </group>
          <group position={[-39.2, 66.97, -106.25]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube5_lambert3_0.geometry} material={nodes.pCube5_lambert3_0.material} />
          </group>
          <group position={[-73.94, 66.97, -106.25]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube6_lambert3_0.geometry} material={nodes.pCube6_lambert3_0.material} />
          </group>
          <group position={[0, 66.97, -106.25]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube7_lambert3_0.geometry} material={nodes.pCube7_lambert3_0.material} />
          </group>
          <group position={[-23.23, 66.97, -72.65]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube8_lambert3_0.geometry} material={nodes.pCube8_lambert3_0.material} />
          </group>
          <group position={[-62.43, 66.97, -72.65]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube9_lambert3_0.geometry} material={nodes.pCube9_lambert3_0.material} />
          </group>
          <group position={[-62.43, 66.97, 71.27]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube10_lambert3_0.geometry} material={nodes.pCube10_lambert3_0.material} />
          </group>
          <group position={[-23.23, 66.97, 71.27]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube11_lambert3_0.geometry} material={nodes.pCube11_lambert3_0.material} />
          </group>
          <group position={[-40.56, 129.26, 0]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube12_lambert3_0.geometry} material={nodes.pCube12_lambert3_0.material} />
          </group>
          <group position={[-40.56, 19.02, 0]} scale={[0.92, 26.32, 0.92]}>
            <mesh geometry={nodes.pCube13_lambert3_0.geometry} material={nodes.pCube13_lambert3_0.material} />
          </group>
        </group>
      </group> */}
    </group>
  )
}

useGLTF.preload('/gltf/bloomlight.gltf')
