/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sikorskymax (https://sketchfab.com/sikorskymax)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hi-tech-corridor-87d0a68deefc407489b176918acebb96
title: Hi-Tech Corridor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gltf/corridor.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
            <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
          </group>
          <group position={[0, 0, 7.06]} scale={[1, 1, 0.33]}>
            <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
          </group>
          <group position={[0, -0.95, 0.45]} scale={[1, 1, 7.23]}>
            <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
          </group>
          <group scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
          </group>
          <group scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
          </group>
          <group scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
          </group>
          <group scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
          </group>
          <group position={[0, 0.94, -6.34]} scale={0.54}>
            <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
          </group>
          <group position={[0, 0.98, -2.69]} scale={0.54}>
            <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
          </group>
          <group position={[0, 0.96, 0.8]} scale={0.54}>
            <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
          </group>
          <group position={[0, 0.95, 5.92]} scale={0.54}>
            <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
          </group>
          <group position={[0, 0, 14.91]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
            <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
          </group>
          <group position={[0, 0, 21.97]} scale={[1, 1, 0.33]}>
            <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
          </group>
          <group position={[0, -0.95, 15.36]} scale={[1, 1, 7.23]}>
            <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
          </group>
          <group position={[0, 0, 14.91]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
          </group>
          <group position={[0, 0, 14.91]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
          </group>
          <group position={[0, 0, 14.91]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
          </group>
          <group position={[0, 0, 14.91]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
          </group>
          <group position={[0, 0.94, 8.57]} scale={0.54}>
            <mesh geometry={nodes.Object_42.geometry} material={nodes.Object_42.material} />
          </group>
          <group position={[0, 0.98, 12.22]} scale={0.54}>
            <mesh geometry={nodes.Object_44.geometry} material={nodes.Object_44.material} />
          </group>
          <group position={[0, 0.96, 15.71]} scale={0.54}>
            <mesh geometry={nodes.Object_46.geometry} material={nodes.Object_46.material} />
          </group>
          <group position={[0, 0.95, 20.83]} scale={0.54}>
            <mesh geometry={nodes.Object_48.geometry} material={nodes.Object_48.material} />
          </group>
          <group position={[0, 0, 29.8]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_50.geometry} material={nodes.Object_50.material} />
            <mesh geometry={nodes.Object_51.geometry} material={nodes.Object_51.material} />
          </group>
          <group position={[0, 0, 36.86]} scale={[1, 1, 0.33]}>
            <mesh geometry={nodes.Object_53.geometry} material={nodes.Object_53.material} />
          </group>
          <group position={[0, -0.95, 30.25]} scale={[1, 1, 7.23]}>
            <mesh geometry={nodes.Object_55.geometry} material={nodes.Object_55.material} />
          </group>
          <group position={[0, 0, 29.8]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_57.geometry} material={nodes.Object_57.material} />
          </group>
          <group position={[0, 0, 29.8]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_59.geometry} material={nodes.Object_59.material} />
          </group>
          <group position={[0, 0, 29.8]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_61.geometry} material={nodes.Object_61.material} />
          </group>
          <group position={[0, 0, 29.8]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_63.geometry} material={nodes.Object_63.material} />
          </group>
          <group position={[0, 0.94, 23.46]} scale={0.54}>
            <mesh geometry={nodes.Object_65.geometry} material={nodes.Object_65.material} />
          </group>
          <group position={[0, 0.98, 27.11]} scale={0.54}>
            <mesh geometry={nodes.Object_67.geometry} material={nodes.Object_67.material} />
          </group>
          <group position={[0, 0.96, 30.6]} scale={0.54}>
            <mesh geometry={nodes.Object_69.geometry} material={nodes.Object_69.material} />
          </group>
          <group position={[0, 0.95, 35.72]} scale={0.54}>
            <mesh geometry={nodes.Object_71.geometry} material={nodes.Object_71.material} />
          </group>
          <group position={[0, 0, 43.66]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_73.geometry} material={nodes.Object_73.material} />
            <mesh geometry={nodes.Object_74.geometry} material={nodes.Object_74.material} />
          </group>
          <group position={[0, 0, 50.72]} scale={[1, 1, 0.33]}>
            <mesh geometry={nodes.Object_76.geometry} material={nodes.Object_76.material} />
          </group>
          <group position={[0, -0.95, 44.11]} scale={[1, 1, 7.23]}>
            <mesh geometry={nodes.Object_78.geometry} material={nodes.Object_78.material} />
          </group>
          <group position={[0, 0, 43.66]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_80.geometry} material={nodes.Object_80.material} />
          </group>
          <group position={[0, 0, 43.66]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_82.geometry} material={nodes.Object_82.material} />
          </group>
          <group position={[0, 0, 43.66]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_84.geometry} material={nodes.Object_84.material} />
          </group>
          <group position={[0, 0, 43.66]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_86.geometry} material={nodes.Object_86.material} />
          </group>
          <group position={[0, 0.94, 37.32]} scale={0.54}>
            <mesh geometry={nodes.Object_88.geometry} material={nodes.Object_88.material} />
          </group>
          <group position={[0, 0.98, 40.97]} scale={0.54}>
            <mesh geometry={nodes.Object_90.geometry} material={nodes.Object_90.material} />
          </group>
          <group position={[0, 0.96, 44.46]} scale={0.54}>
            <mesh geometry={nodes.Object_92.geometry} material={nodes.Object_92.material} />
          </group>
          <group position={[0, 0.95, 49.58]} scale={0.54}>
            <mesh geometry={nodes.Object_94.geometry} material={nodes.Object_94.material} />
          </group>
          <group position={[0, 0, 58.57]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_96.geometry} material={nodes.Object_96.material} />
            <mesh geometry={nodes.Object_97.geometry} material={nodes.Object_97.material} />
          </group>
          <group position={[0, 0, 65.63]} scale={[1, 1, 0.33]}>
            <mesh geometry={nodes.Object_99.geometry} material={nodes.Object_99.material} />
          </group>
          <group position={[0, -0.95, 59.02]} scale={[1, 1, 7.23]}>
            <mesh geometry={nodes.Object_101.geometry} material={nodes.Object_101.material} />
          </group>
          <group position={[0, 0, 58.57]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_103.geometry} material={nodes.Object_103.material} />
          </group>
          <group position={[0, 0, 58.57]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_105.geometry} material={nodes.Object_105.material} />
          </group>
          <group position={[0, 0, 58.57]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_107.geometry} material={nodes.Object_107.material} />
          </group>
          <group position={[0, 0, 58.57]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_109.geometry} material={nodes.Object_109.material} />
          </group>
          <group position={[0, 0.94, 52.23]} scale={0.54}>
            <mesh geometry={nodes.Object_111.geometry} material={nodes.Object_111.material} />
          </group>
          <group position={[0, 0.98, 55.88]} scale={0.54}>
            <mesh geometry={nodes.Object_113.geometry} material={nodes.Object_113.material} />
          </group>
          <group position={[0, 0.96, 59.37]} scale={0.54}>
            <mesh geometry={nodes.Object_115.geometry} material={nodes.Object_115.material} />
          </group>
          <group position={[0, 0.95, 64.49]} scale={0.54}>
            <mesh geometry={nodes.Object_117.geometry} material={nodes.Object_117.material} />
          </group>
          <group position={[0, 0, 73.46]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_119.geometry} material={nodes.Object_119.material} />
            <mesh geometry={nodes.Object_120.geometry} material={nodes.Object_120.material} />
          </group>
          <group position={[0, 0, 80.52]} scale={[1, 1, 0.33]}>
            <mesh geometry={nodes.Object_122.geometry} material={nodes.Object_122.material} />
          </group>
          <group position={[0, -0.95, 73.91]} scale={[1, 1, 7.23]}>
            <mesh geometry={nodes.Object_124.geometry} material={nodes.Object_124.material} />
          </group>
          <group position={[0, 0, 73.46]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_126.geometry} material={nodes.Object_126.material} />
          </group>
          <group position={[0, 0, 73.46]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_128.geometry} material={nodes.Object_128.material} />
          </group>
          <group position={[0, 0, 73.46]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_130.geometry} material={nodes.Object_130.material} />
          </group>
          <group position={[0, 0, 73.46]} scale={[1, 1, 7.39]}>
            <mesh geometry={nodes.Object_132.geometry} material={nodes.Object_132.material} />
          </group>
          <group position={[0, 0.94, 67.12]} scale={0.54}>
            <mesh geometry={nodes.Object_134.geometry} material={nodes.Object_134.material} />
          </group>
          <group position={[0, 0.98, 70.77]} scale={0.54}>
            <mesh geometry={nodes.Object_136.geometry} material={nodes.Object_136.material} />
          </group>
          <group position={[0, 0.96, 74.26]} scale={0.54}>
            <mesh geometry={nodes.Object_138.geometry} material={nodes.Object_138.material} />
          </group>
          <group position={[0, 0.95, 79.38]} scale={0.54}>
            <mesh geometry={nodes.Object_140.geometry} material={nodes.Object_140.material} />
          </group>
          <group position={[0.7, -0.83, 0.01]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_142.geometry} material={nodes.Object_142.material} />
          </group>
          <group position={[0.75, -0.78, 0.01]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_144.geometry} material={nodes.Object_144.material} />
          </group>
          <group position={[0.79, -0.72, 0.01]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_146.geometry} material={nodes.Object_146.material} />
          </group>
          <group position={[0.66, -0.91, 0.01]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_148.geometry} material={nodes.Object_148.material} />
          </group>
          <group position={[0.88, -0.68, 0.03]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_150.geometry} material={nodes.Object_150.material} />
          </group>
          <group position={[0.7, -0.83, 14.92]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_152.geometry} material={nodes.Object_152.material} />
          </group>
          <group position={[0.75, -0.78, 14.92]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_154.geometry} material={nodes.Object_154.material} />
          </group>
          <group position={[0.79, -0.72, 14.92]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_156.geometry} material={nodes.Object_156.material} />
          </group>
          <group position={[0.66, -0.91, 14.92]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_158.geometry} material={nodes.Object_158.material} />
          </group>
          <group position={[0.88, -0.68, 14.94]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_160.geometry} material={nodes.Object_160.material} />
          </group>
          <group position={[0.7, -0.83, 29.81]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_162.geometry} material={nodes.Object_162.material} />
          </group>
          <group position={[0.75, -0.78, 29.81]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_164.geometry} material={nodes.Object_164.material} />
          </group>
          <group position={[0.79, -0.72, 29.81]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_166.geometry} material={nodes.Object_166.material} />
          </group>
          <group position={[0.66, -0.91, 29.81]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_168.geometry} material={nodes.Object_168.material} />
          </group>
          <group position={[0.88, -0.68, 29.83]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_170.geometry} material={nodes.Object_170.material} />
          </group>
          <group position={[0.7, -0.83, 43.67]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_172.geometry} material={nodes.Object_172.material} />
          </group>
          <group position={[0.75, -0.78, 43.67]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_174.geometry} material={nodes.Object_174.material} />
          </group>
          <group position={[0.79, -0.72, 43.68]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_176.geometry} material={nodes.Object_176.material} />
          </group>
          <group position={[0.66, -0.91, 43.67]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_178.geometry} material={nodes.Object_178.material} />
          </group>
          <group position={[0.88, -0.68, 43.69]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_180.geometry} material={nodes.Object_180.material} />
          </group>
          <group position={[0.7, -0.83, 58.58]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_182.geometry} material={nodes.Object_182.material} />
          </group>
          <group position={[0.75, -0.78, 58.58]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_184.geometry} material={nodes.Object_184.material} />
          </group>
          <group position={[0.79, -0.72, 58.59]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_186.geometry} material={nodes.Object_186.material} />
          </group>
          <group position={[0.66, -0.91, 58.58]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_188.geometry} material={nodes.Object_188.material} />
          </group>
          <group position={[0.88, -0.68, 58.6]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_190.geometry} material={nodes.Object_190.material} />
          </group>
          <group position={[0.7, -0.83, 73.47]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_192.geometry} material={nodes.Object_192.material} />
          </group>
          <group position={[0.75, -0.78, 73.47]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_194.geometry} material={nodes.Object_194.material} />
          </group>
          <group position={[0.79, -0.72, 73.48]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_196.geometry} material={nodes.Object_196.material} />
          </group>
          <group position={[0.66, -0.91, 73.47]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_198.geometry} material={nodes.Object_198.material} />
          </group>
          <group position={[0.88, -0.68, 73.49]} rotation={[0, Math.PI / 2, 0]} scale={3.76}>
            <mesh geometry={nodes.Object_200.geometry} material={nodes.Object_200.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gltf/corridor.gltf')
