/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cyber-cubes-leave-camera-alone-8a3cea4da2184b5bb5bf68add9e28375
title: Cyber Cubes (Leave Camera Alone)
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/gltf/cube.gltf");
  const { actions, ref, mixer, clips, names } = useAnimations(
    animations,
    group
  );
  useEffect(() => {
    console.log(mixer.clipAction);
    console.log(actions.Animation);
    // nodes.map(node => console.log(node))
    // console.log(Object.keys(nodes));
    // let i = 2;
    // Object.keys(nodes).forEach((node) => {
    //   if (nodes[node].type == "Mesh") {
    //     console.log(nodes[node]);
    //     i += 1;
    //     // console.log(nodes[node]);
    //     if (i % 3 === 0) nodes[node].material.color.set(0x00ff00);
    //     // else nodes[node].material.color.set(0xff0000);
    //     // nodes[node].actions.play()
    //   }
    //   // console.log(nodes[node].type == "Mesh");
    // });

    // console.log(mixer.clipAction(clips))
    // const action = mixer.clipAction(animations[0]);
    // clips.forEach(function (clip) {
    //   mixer.clipAction(clip,group.current).play();
    // });
  });

  // useEffect(() => {
  //   // Reset and fade in animation after an index has been changed
  //   actions[names[index]].reset().fadeIn(0.5).play();
  //   // In the clean-up phase, fade it out
  //   return () => actions[names[index]].fadeOut(0.5);
  // }, [index, actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1, 1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={nodes.Object_4.material}
            />
          </group>
          <group position={[-1, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_6.geometry}
              material={nodes.Object_6.material}
            />
          </group>
          <group position={[1, -1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_8.geometry}
              material={nodes.Object_8.material}
            />
          </group>
          <group position={[1, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_10.geometry}
              material={nodes.Object_10.material}
            />
          </group>
          <group position={[-1, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_14.geometry}
              material={nodes.Object_14.material}
            />
          </group>
          <group position={[-1, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_16.geometry}
              material={nodes.Object_16.material}
            />
          </group>
          <group position={[1, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_18.geometry}
              material={nodes.Object_18.material}
            />
          </group>
          <group position={[1, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_20.geometry}
              material={nodes.Object_20.material}
            />
          </group>
          <group position={[-1, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_24.geometry}
              material={nodes.Object_24.material}
            />
          </group>
          <group position={[-1, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_26.geometry}
              material={nodes.Object_26.material}
            />
          </group>
          <group position={[1, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_28.geometry}
              material={nodes.Object_28.material}
            />
          </group>
          <group position={[1, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_30.geometry}
              material={nodes.Object_30.material}
            />
          </group>
          <group position={[-1, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_34.geometry}
              material={nodes.Object_34.material}
            />
          </group>
          <group position={[-1, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_36.geometry}
              material={nodes.Object_36.material}
            />
          </group>
          <group position={[1, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_38.geometry}
              material={nodes.Object_38.material}
            />
          </group>
          <group position={[1, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_40.geometry}
              material={nodes.Object_40.material}
            />
          </group>
          <group position={[-1, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_44.geometry}
              material={nodes.Object_44.material}
            />
          </group>
          <group position={[-1, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_46.geometry}
              material={nodes.Object_46.material}
            />
          </group>
          <group position={[1, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_48.geometry}
              material={nodes.Object_48.material}
            />
          </group>
          <group position={[1, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_50.geometry}
              material={nodes.Object_50.material}
            />
          </group>
          <group position={[-1, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_54.geometry}
              material={nodes.Object_54.material}
            />
          </group>
          <group position={[-1, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_56.geometry}
              material={nodes.Object_56.material}
            />
          </group>
          <group position={[1, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_58.geometry}
              material={nodes.Object_58.material}
            />
          </group>
          <group position={[1, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_60.geometry}
              material={nodes.Object_60.material}
            />
          </group>
          <group position={[-1, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_64.geometry}
              material={nodes.Object_64.material}
            />
          </group>
          <group position={[-1, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_66.geometry}
              material={nodes.Object_66.material}
            />
          </group>
          <group position={[1, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_68.geometry}
              material={nodes.Object_68.material}
            />
          </group>
          <group position={[1, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_70.geometry}
              material={nodes.Object_70.material}
            />
          </group>
          <group position={[-1, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_74.geometry}
              material={nodes.Object_74.material}
            />
          </group>
          <group position={[-1, -1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_76.geometry}
              material={nodes.Object_76.material}
            />
          </group>
          <group position={[1, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_78.geometry}
              material={nodes.Object_78.material}
            />
          </group>
          <group position={[1, 1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_80.geometry}
              material={nodes.Object_80.material}
            />
          </group>
          <group position={[-1, 1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_84.geometry}
              material={nodes.Object_84.material}
            />
          </group>
          <group position={[-1, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_86.geometry}
              material={nodes.Object_86.material}
            />
          </group>
          <group position={[1, -1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_88.geometry}
              material={nodes.Object_88.material}
            />
          </group>
          <group position={[1, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_90.geometry}
              material={nodes.Object_90.material}
            />
          </group>
          <group position={[-1, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_94.geometry}
              material={nodes.Object_94.material}
            />
          </group>
          <group position={[-1, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_96.geometry}
              material={nodes.Object_96.material}
            />
          </group>
          <group position={[1, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_98.geometry}
              material={nodes.Object_98.material}
            />
          </group>
          <group position={[1, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_100.geometry}
              material={nodes.Object_100.material}
            />
          </group>
          <group position={[-1, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_104.geometry}
              material={nodes.Object_104.material}
            />
          </group>
          <group position={[-1, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_106.geometry}
              material={nodes.Object_106.material}
            />
          </group>
          <group position={[1, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_108.geometry}
              material={nodes.Object_108.material}
            />
          </group>
          <group position={[1, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_110.geometry}
              material={nodes.Object_110.material}
            />
          </group>
          <group position={[-1, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_114.geometry}
              material={nodes.Object_114.material}
            />
          </group>
          <group position={[-1, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_116.geometry}
              material={nodes.Object_116.material}
            />
          </group>
          <group position={[1, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_118.geometry}
              material={nodes.Object_118.material}
            />
          </group>
          <group position={[1, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_120.geometry}
              material={nodes.Object_120.material}
            />
          </group>
          <group position={[-1, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_124.geometry}
              material={nodes.Object_124.material}
            />
          </group>
          <group position={[-1, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_126.geometry}
              material={nodes.Object_126.material}
            />
          </group>
          <group position={[1, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_128.geometry}
              material={nodes.Object_128.material}
            />
          </group>
          <group position={[1, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_130.geometry}
              material={nodes.Object_130.material}
            />
          </group>
          <group position={[-1, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_134.geometry}
              material={nodes.Object_134.material}
            />
          </group>
          <group position={[-1, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_136.geometry}
              material={nodes.Object_136.material}
            />
          </group>
          <group position={[1, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_138.geometry}
              material={nodes.Object_138.material}
            />
          </group>
          <group position={[1, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_140.geometry}
              material={nodes.Object_140.material}
            />
          </group>
          <group position={[-1, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_144.geometry}
              material={nodes.Object_144.material}
            />
          </group>
          <group position={[-1, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_146.geometry}
              material={nodes.Object_146.material}
            />
          </group>
          <group position={[1, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_148.geometry}
              material={nodes.Object_148.material}
            />
          </group>
          <group position={[1, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_150.geometry}
              material={nodes.Object_150.material}
            />
          </group>
          <group position={[-1, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_154.geometry}
              material={nodes.Object_154.material}
            />
          </group>
          <group position={[-1, -1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_156.geometry}
              material={nodes.Object_156.material}
            />
          </group>
          <group position={[1, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_158.geometry}
              material={nodes.Object_158.material}
            />
          </group>
          <group position={[1, 1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_160.geometry}
              material={nodes.Object_160.material}
            />
          </group>
          <group position={[-1, 7, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_164.geometry}
              material={nodes.Object_164.material}
            />
          </group>
          <group position={[-1, 5, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_166.geometry}
              material={nodes.Object_166.material}
            />
          </group>
          <group position={[1, 5, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_168.geometry}
              material={nodes.Object_168.material}
            />
          </group>
          <group position={[1, 7, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_170.geometry}
              material={nodes.Object_170.material}
            />
          </group>
          <group position={[-1, 7, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_174.geometry}
              material={nodes.Object_174.material}
            />
          </group>
          <group position={[-1, 5, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_176.geometry}
              material={nodes.Object_176.material}
            />
          </group>
          <group position={[1, 5, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_178.geometry}
              material={nodes.Object_178.material}
            />
          </group>
          <group position={[1, 7, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_180.geometry}
              material={nodes.Object_180.material}
            />
          </group>
          <group position={[-1, 7, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_184.geometry}
              material={nodes.Object_184.material}
            />
          </group>
          <group position={[-1, 5, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_186.geometry}
              material={nodes.Object_186.material}
            />
          </group>
          <group position={[1, 5, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_188.geometry}
              material={nodes.Object_188.material}
            />
          </group>
          <group position={[1, 7, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_190.geometry}
              material={nodes.Object_190.material}
            />
          </group>
          <group position={[-1, 7, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_194.geometry}
              material={nodes.Object_194.material}
            />
          </group>
          <group position={[-1, 5, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_196.geometry}
              material={nodes.Object_196.material}
            />
          </group>
          <group position={[1, 5, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_198.geometry}
              material={nodes.Object_198.material}
            />
          </group>
          <group position={[1, 7, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_200.geometry}
              material={nodes.Object_200.material}
            />
          </group>
          <group position={[-1, 7, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_204.geometry}
              material={nodes.Object_204.material}
            />
          </group>
          <group position={[-1, 5, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_206.geometry}
              material={nodes.Object_206.material}
            />
          </group>
          <group position={[1, 5, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_208.geometry}
              material={nodes.Object_208.material}
            />
          </group>
          <group position={[1, 7, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_210.geometry}
              material={nodes.Object_210.material}
            />
          </group>
          <group position={[-1, 7, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_214.geometry}
              material={nodes.Object_214.material}
            />
          </group>
          <group position={[-1, 5, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_216.geometry}
              material={nodes.Object_216.material}
            />
          </group>
          <group position={[1, 5, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_218.geometry}
              material={nodes.Object_218.material}
            />
          </group>
          <group position={[1, 7, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_220.geometry}
              material={nodes.Object_220.material}
            />
          </group>
          <group position={[-1, 7, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_224.geometry}
              material={nodes.Object_224.material}
            />
          </group>
          <group position={[-1, 5, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_226.geometry}
              material={nodes.Object_226.material}
            />
          </group>
          <group position={[1, 5, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_228.geometry}
              material={nodes.Object_228.material}
            />
          </group>
          <group position={[1, 7, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_230.geometry}
              material={nodes.Object_230.material}
            />
          </group>
          <group position={[-1, 7, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_234.geometry}
              material={nodes.Object_234.material}
            />
          </group>
          <group position={[-1, 5, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_236.geometry}
              material={nodes.Object_236.material}
            />
          </group>
          <group position={[1, 5, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_238.geometry}
              material={nodes.Object_238.material}
            />
          </group>
          <group position={[1, 7, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_240.geometry}
              material={nodes.Object_240.material}
            />
          </group>
          <group position={[-1, 7, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_244.geometry}
              material={nodes.Object_244.material}
            />
          </group>
          <group position={[-1, 5, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_246.geometry}
              material={nodes.Object_246.material}
            />
          </group>
          <group position={[1, 5, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_248.geometry}
              material={nodes.Object_248.material}
            />
          </group>
          <group position={[1, 7, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_250.geometry}
              material={nodes.Object_250.material}
            />
          </group>
          <group position={[-1, 7, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_254.geometry}
              material={nodes.Object_254.material}
            />
          </group>
          <group position={[-1, 5, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_256.geometry}
              material={nodes.Object_256.material}
            />
          </group>
          <group position={[1, 5, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_258.geometry}
              material={nodes.Object_258.material}
            />
          </group>
          <group position={[1, 7, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_260.geometry}
              material={nodes.Object_260.material}
            />
          </group>
          <group position={[-1, 7, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_264.geometry}
              material={nodes.Object_264.material}
            />
          </group>
          <group position={[-1, 5, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_266.geometry}
              material={nodes.Object_266.material}
            />
          </group>
          <group position={[1, 5, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_268.geometry}
              material={nodes.Object_268.material}
            />
          </group>
          <group position={[1, 7, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_270.geometry}
              material={nodes.Object_270.material}
            />
          </group>
          <group position={[-1, 7, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_274.geometry}
              material={nodes.Object_274.material}
            />
          </group>
          <group position={[-1, 5, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_276.geometry}
              material={nodes.Object_276.material}
            />
          </group>
          <group position={[1, 5, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_278.geometry}
              material={nodes.Object_278.material}
            />
          </group>
          <group position={[1, 7, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_280.geometry}
              material={nodes.Object_280.material}
            />
          </group>
          <group position={[-1, 7, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_284.geometry}
              material={nodes.Object_284.material}
            />
          </group>
          <group position={[-1, 5, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_286.geometry}
              material={nodes.Object_286.material}
            />
          </group>
          <group position={[1, 5, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_288.geometry}
              material={nodes.Object_288.material}
            />
          </group>
          <group position={[1, 7, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_290.geometry}
              material={nodes.Object_290.material}
            />
          </group>
          <group position={[-1, 7, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_294.geometry}
              material={nodes.Object_294.material}
            />
          </group>
          <group position={[-1, 5, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_296.geometry}
              material={nodes.Object_296.material}
            />
          </group>
          <group position={[1, 5, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_298.geometry}
              material={nodes.Object_298.material}
            />
          </group>
          <group position={[1, 7, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_300.geometry}
              material={nodes.Object_300.material}
            />
          </group>
          <group position={[-1, 7, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_304.geometry}
              material={nodes.Object_304.material}
            />
          </group>
          <group position={[-1, 5, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_306.geometry}
              material={nodes.Object_306.material}
            />
          </group>
          <group position={[1, 5, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_308.geometry}
              material={nodes.Object_308.material}
            />
          </group>
          <group position={[1, 7, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_310.geometry}
              material={nodes.Object_310.material}
            />
          </group>
          <group position={[-1, 7, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_314.geometry}
              material={nodes.Object_314.material}
            />
          </group>
          <group position={[-1, 5, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_316.geometry}
              material={nodes.Object_316.material}
            />
          </group>
          <group position={[1, 5, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_318.geometry}
              material={nodes.Object_318.material}
            />
          </group>
          <group position={[1, 7, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_320.geometry}
              material={nodes.Object_320.material}
            />
          </group>
          <group position={[-7, 1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_324.geometry}
              material={nodes.Object_324.material}
            />
          </group>
          <group position={[-7, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_326.geometry}
              material={nodes.Object_326.material}
            />
          </group>
          <group position={[-5, -1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_328.geometry}
              material={nodes.Object_328.material}
            />
          </group>
          <group position={[-5, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_330.geometry}
              material={nodes.Object_330.material}
            />
          </group>
          <group position={[-7, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_334.geometry}
              material={nodes.Object_334.material}
            />
          </group>
          <group position={[-7, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_336.geometry}
              material={nodes.Object_336.material}
            />
          </group>
          <group position={[-5, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_338.geometry}
              material={nodes.Object_338.material}
            />
          </group>
          <group position={[-5, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_340.geometry}
              material={nodes.Object_340.material}
            />
          </group>
          <group position={[-7, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_344.geometry}
              material={nodes.Object_344.material}
            />
          </group>
          <group position={[-7, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_346.geometry}
              material={nodes.Object_346.material}
            />
          </group>
          <group position={[-5, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_348.geometry}
              material={nodes.Object_348.material}
            />
          </group>
          <group position={[-5, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_350.geometry}
              material={nodes.Object_350.material}
            />
          </group>
          <group position={[-7, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_354.geometry}
              material={nodes.Object_354.material}
            />
          </group>
          <group position={[-7, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_356.geometry}
              material={nodes.Object_356.material}
            />
          </group>
          <group position={[-5, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_358.geometry}
              material={nodes.Object_358.material}
            />
          </group>
          <group position={[-5, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_360.geometry}
              material={nodes.Object_360.material}
            />
          </group>
          <group position={[-7, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_364.geometry}
              material={nodes.Object_364.material}
            />
          </group>
          <group position={[-7, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_366.geometry}
              material={nodes.Object_366.material}
            />
          </group>
          <group position={[-5, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_368.geometry}
              material={nodes.Object_368.material}
            />
          </group>
          <group position={[-5, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_370.geometry}
              material={nodes.Object_370.material}
            />
          </group>
          <group position={[-7, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_374.geometry}
              material={nodes.Object_374.material}
            />
          </group>
          <group position={[-7, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_376.geometry}
              material={nodes.Object_376.material}
            />
          </group>
          <group position={[-5, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_378.geometry}
              material={nodes.Object_378.material}
            />
          </group>
          <group position={[-5, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_380.geometry}
              material={nodes.Object_380.material}
            />
          </group>
          <group position={[-7, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_384.geometry}
              material={nodes.Object_384.material}
            />
          </group>
          <group position={[-7, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_386.geometry}
              material={nodes.Object_386.material}
            />
          </group>
          <group position={[-5, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_388.geometry}
              material={nodes.Object_388.material}
            />
          </group>
          <group position={[-5, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_390.geometry}
              material={nodes.Object_390.material}
            />
          </group>
          <group position={[-7, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_394.geometry}
              material={nodes.Object_394.material}
            />
          </group>
          <group position={[-7, -1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_396.geometry}
              material={nodes.Object_396.material}
            />
          </group>
          <group position={[-5, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_398.geometry}
              material={nodes.Object_398.material}
            />
          </group>
          <group position={[-5, 1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_400.geometry}
              material={nodes.Object_400.material}
            />
          </group>
          <group position={[-7, 1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_404.geometry}
              material={nodes.Object_404.material}
            />
          </group>
          <group position={[-7, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_406.geometry}
              material={nodes.Object_406.material}
            />
          </group>
          <group position={[-5, -1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_408.geometry}
              material={nodes.Object_408.material}
            />
          </group>
          <group position={[-5, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_410.geometry}
              material={nodes.Object_410.material}
            />
          </group>
          <group position={[-7, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_414.geometry}
              material={nodes.Object_414.material}
            />
          </group>
          <group position={[-7, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_416.geometry}
              material={nodes.Object_416.material}
            />
          </group>
          <group position={[-5, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_418.geometry}
              material={nodes.Object_418.material}
            />
          </group>
          <group position={[-5, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_420.geometry}
              material={nodes.Object_420.material}
            />
          </group>
          <group position={[-7, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_424.geometry}
              material={nodes.Object_424.material}
            />
          </group>
          <group position={[-7, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_426.geometry}
              material={nodes.Object_426.material}
            />
          </group>
          <group position={[-5, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_428.geometry}
              material={nodes.Object_428.material}
            />
          </group>
          <group position={[-5, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_430.geometry}
              material={nodes.Object_430.material}
            />
          </group>
          <group position={[-7, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_434.geometry}
              material={nodes.Object_434.material}
            />
          </group>
          <group position={[-7, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_436.geometry}
              material={nodes.Object_436.material}
            />
          </group>
          <group position={[-5, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_438.geometry}
              material={nodes.Object_438.material}
            />
          </group>
          <group position={[-5, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_440.geometry}
              material={nodes.Object_440.material}
            />
          </group>
          <group position={[-7, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_444.geometry}
              material={nodes.Object_444.material}
            />
          </group>
          <group position={[-7, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_446.geometry}
              material={nodes.Object_446.material}
            />
          </group>
          <group position={[-5, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_448.geometry}
              material={nodes.Object_448.material}
            />
          </group>
          <group position={[-5, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_450.geometry}
              material={nodes.Object_450.material}
            />
          </group>
          <group position={[-7, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_454.geometry}
              material={nodes.Object_454.material}
            />
          </group>
          <group position={[-7, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_456.geometry}
              material={nodes.Object_456.material}
            />
          </group>
          <group position={[-5, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_458.geometry}
              material={nodes.Object_458.material}
            />
          </group>
          <group position={[-5, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_460.geometry}
              material={nodes.Object_460.material}
            />
          </group>
          <group position={[-7, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_464.geometry}
              material={nodes.Object_464.material}
            />
          </group>
          <group position={[-7, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_466.geometry}
              material={nodes.Object_466.material}
            />
          </group>
          <group position={[-5, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_468.geometry}
              material={nodes.Object_468.material}
            />
          </group>
          <group position={[-5, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_470.geometry}
              material={nodes.Object_470.material}
            />
          </group>
          <group position={[-7, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_474.geometry}
              material={nodes.Object_474.material}
            />
          </group>
          <group position={[-7, -1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_476.geometry}
              material={nodes.Object_476.material}
            />
          </group>
          <group position={[-5, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_478.geometry}
              material={nodes.Object_478.material}
            />
          </group>
          <group position={[-5, 1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_480.geometry}
              material={nodes.Object_480.material}
            />
          </group>
          <group position={[5.1, 1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_484.geometry}
              material={nodes.Object_484.material}
            />
          </group>
          <group position={[5.1, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_486.geometry}
              material={nodes.Object_486.material}
            />
          </group>
          <group position={[7.1, -1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_488.geometry}
              material={nodes.Object_488.material}
            />
          </group>
          <group position={[7.1, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_490.geometry}
              material={nodes.Object_490.material}
            />
          </group>
          <group position={[5.1, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_494.geometry}
              material={nodes.Object_494.material}
            />
          </group>
          <group position={[5.1, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_496.geometry}
              material={nodes.Object_496.material}
            />
          </group>
          <group position={[7.1, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_498.geometry}
              material={nodes.Object_498.material}
            />
          </group>
          <group position={[7.1, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_500.geometry}
              material={nodes.Object_500.material}
            />
          </group>
          <group position={[5.1, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_504.geometry}
              material={nodes.Object_504.material}
            />
          </group>
          <group position={[5.1, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_506.geometry}
              material={nodes.Object_506.material}
            />
          </group>
          <group position={[7.1, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_508.geometry}
              material={nodes.Object_508.material}
            />
          </group>
          <group position={[7.1, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_510.geometry}
              material={nodes.Object_510.material}
            />
          </group>
          <group position={[5.1, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_514.geometry}
              material={nodes.Object_514.material}
            />
          </group>
          <group position={[5.1, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_516.geometry}
              material={nodes.Object_516.material}
            />
          </group>
          <group position={[7.1, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_518.geometry}
              material={nodes.Object_518.material}
            />
          </group>
          <group position={[7.1, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_520.geometry}
              material={nodes.Object_520.material}
            />
          </group>
          <group position={[5.1, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_524.geometry}
              material={nodes.Object_524.material}
            />
          </group>
          <group position={[5.1, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_526.geometry}
              material={nodes.Object_526.material}
            />
          </group>
          <group position={[7.1, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_528.geometry}
              material={nodes.Object_528.material}
            />
          </group>
          <group position={[7.1, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_530.geometry}
              material={nodes.Object_530.material}
            />
          </group>
          <group position={[5.1, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_534.geometry}
              material={nodes.Object_534.material}
            />
          </group>
          <group position={[5.1, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_536.geometry}
              material={nodes.Object_536.material}
            />
          </group>
          <group position={[7.1, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_538.geometry}
              material={nodes.Object_538.material}
            />
          </group>
          <group position={[7.1, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_540.geometry}
              material={nodes.Object_540.material}
            />
          </group>
          <group position={[5.1, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_544.geometry}
              material={nodes.Object_544.material}
            />
          </group>
          <group position={[5.1, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_546.geometry}
              material={nodes.Object_546.material}
            />
          </group>
          <group position={[7.1, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_548.geometry}
              material={nodes.Object_548.material}
            />
          </group>
          <group position={[7.1, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_550.geometry}
              material={nodes.Object_550.material}
            />
          </group>
          <group position={[5.1, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_554.geometry}
              material={nodes.Object_554.material}
            />
          </group>
          <group position={[5.1, -1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_556.geometry}
              material={nodes.Object_556.material}
            />
          </group>
          <group position={[7.1, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_558.geometry}
              material={nodes.Object_558.material}
            />
          </group>
          <group position={[7.1, 1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_560.geometry}
              material={nodes.Object_560.material}
            />
          </group>
          <group position={[5.1, 1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_564.geometry}
              material={nodes.Object_564.material}
            />
          </group>
          <group position={[5.1, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_566.geometry}
              material={nodes.Object_566.material}
            />
          </group>
          <group position={[7.1, -1, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_568.geometry}
              material={nodes.Object_568.material}
            />
          </group>
          <group position={[7.1, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_570.geometry}
              material={nodes.Object_570.material}
            />
          </group>
          <group position={[5.1, 1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_574.geometry}
              material={nodes.Object_574.material}
            />
          </group>
          <group position={[5.1, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_576.geometry}
              material={nodes.Object_576.material}
            />
          </group>
          <group position={[7.1, -1, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_578.geometry}
              material={nodes.Object_578.material}
            />
          </group>
          <group position={[7.1, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_580.geometry}
              material={nodes.Object_580.material}
            />
          </group>
          <group position={[5.1, 1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_584.geometry}
              material={nodes.Object_584.material}
            />
          </group>
          <group position={[5.1, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_586.geometry}
              material={nodes.Object_586.material}
            />
          </group>
          <group position={[7.1, -1, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_588.geometry}
              material={nodes.Object_588.material}
            />
          </group>
          <group position={[7.1, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_590.geometry}
              material={nodes.Object_590.material}
            />
          </group>
          <group position={[5.1, 1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_594.geometry}
              material={nodes.Object_594.material}
            />
          </group>
          <group position={[5.1, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_596.geometry}
              material={nodes.Object_596.material}
            />
          </group>
          <group position={[7.1, -1, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_598.geometry}
              material={nodes.Object_598.material}
            />
          </group>
          <group position={[7.1, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_600.geometry}
              material={nodes.Object_600.material}
            />
          </group>
          <group position={[5.1, 1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_604.geometry}
              material={nodes.Object_604.material}
            />
          </group>
          <group position={[5.1, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_606.geometry}
              material={nodes.Object_606.material}
            />
          </group>
          <group position={[7.1, -1, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_608.geometry}
              material={nodes.Object_608.material}
            />
          </group>
          <group position={[7.1, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_610.geometry}
              material={nodes.Object_610.material}
            />
          </group>
          <group position={[5.1, 1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_614.geometry}
              material={nodes.Object_614.material}
            />
          </group>
          <group position={[5.1, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_616.geometry}
              material={nodes.Object_616.material}
            />
          </group>
          <group position={[7.1, -1, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_618.geometry}
              material={nodes.Object_618.material}
            />
          </group>
          <group position={[7.1, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_620.geometry}
              material={nodes.Object_620.material}
            />
          </group>
          <group position={[5.1, 1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_624.geometry}
              material={nodes.Object_624.material}
            />
          </group>
          <group position={[5.1, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_626.geometry}
              material={nodes.Object_626.material}
            />
          </group>
          <group position={[7.1, -1, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_628.geometry}
              material={nodes.Object_628.material}
            />
          </group>
          <group position={[7.1, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_630.geometry}
              material={nodes.Object_630.material}
            />
          </group>
          <group position={[5.1, 1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_634.geometry}
              material={nodes.Object_634.material}
            />
          </group>
          <group position={[5.1, -1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_636.geometry}
              material={nodes.Object_636.material}
            />
          </group>
          <group position={[7.1, -1, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_638.geometry}
              material={nodes.Object_638.material}
            />
          </group>
          <group position={[7.1, 1, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_640.geometry}
              material={nodes.Object_640.material}
            />
          </group>
          <group position={[-1, -5, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_644.geometry}
              material={nodes.Object_644.material}
            />
          </group>
          <group position={[-1, -7, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_646.geometry}
              material={nodes.Object_646.material}
            />
          </group>
          <group position={[1, -7, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_648.geometry}
              material={nodes.Object_648.material}
            />
          </group>
          <group position={[1, -5, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_650.geometry}
              material={nodes.Object_650.material}
            />
          </group>
          <group position={[-1, -5, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_654.geometry}
              material={nodes.Object_654.material}
            />
          </group>
          <group position={[-1, -7, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_656.geometry}
              material={nodes.Object_656.material}
            />
          </group>
          <group position={[1, -7, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_658.geometry}
              material={nodes.Object_658.material}
            />
          </group>
          <group position={[1, -5, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_660.geometry}
              material={nodes.Object_660.material}
            />
          </group>
          <group position={[-1, -5, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_664.geometry}
              material={nodes.Object_664.material}
            />
          </group>
          <group position={[-1, -7, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_666.geometry}
              material={nodes.Object_666.material}
            />
          </group>
          <group position={[1, -7, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_668.geometry}
              material={nodes.Object_668.material}
            />
          </group>
          <group position={[1, -5, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_670.geometry}
              material={nodes.Object_670.material}
            />
          </group>
          <group position={[-1, -5, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_674.geometry}
              material={nodes.Object_674.material}
            />
          </group>
          <group position={[-1, -7, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_676.geometry}
              material={nodes.Object_676.material}
            />
          </group>
          <group position={[1, -7, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_678.geometry}
              material={nodes.Object_678.material}
            />
          </group>
          <group position={[1, -5, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_680.geometry}
              material={nodes.Object_680.material}
            />
          </group>
          <group position={[-1, -5, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_684.geometry}
              material={nodes.Object_684.material}
            />
          </group>
          <group position={[-1, -7, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_686.geometry}
              material={nodes.Object_686.material}
            />
          </group>
          <group position={[1, -7, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_688.geometry}
              material={nodes.Object_688.material}
            />
          </group>
          <group position={[1, -5, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_690.geometry}
              material={nodes.Object_690.material}
            />
          </group>
          <group position={[-1, -5, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_694.geometry}
              material={nodes.Object_694.material}
            />
          </group>
          <group position={[-1, -7, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_696.geometry}
              material={nodes.Object_696.material}
            />
          </group>
          <group position={[1, -7, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_698.geometry}
              material={nodes.Object_698.material}
            />
          </group>
          <group position={[1, -5, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_700.geometry}
              material={nodes.Object_700.material}
            />
          </group>
          <group position={[-1, -5, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_704.geometry}
              material={nodes.Object_704.material}
            />
          </group>
          <group position={[-1, -7, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_706.geometry}
              material={nodes.Object_706.material}
            />
          </group>
          <group position={[1, -7, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_708.geometry}
              material={nodes.Object_708.material}
            />
          </group>
          <group position={[1, -5, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_710.geometry}
              material={nodes.Object_710.material}
            />
          </group>
          <group position={[-1, -5, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_714.geometry}
              material={nodes.Object_714.material}
            />
          </group>
          <group position={[-1, -7, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_716.geometry}
              material={nodes.Object_716.material}
            />
          </group>
          <group position={[1, -7, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_718.geometry}
              material={nodes.Object_718.material}
            />
          </group>
          <group position={[1, -5, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_720.geometry}
              material={nodes.Object_720.material}
            />
          </group>
          <group position={[-1, -5, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_724.geometry}
              material={nodes.Object_724.material}
            />
          </group>
          <group position={[-1, -7, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_726.geometry}
              material={nodes.Object_726.material}
            />
          </group>
          <group position={[1, -7, 1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_728.geometry}
              material={nodes.Object_728.material}
            />
          </group>
          <group position={[1, -5, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_730.geometry}
              material={nodes.Object_730.material}
            />
          </group>
          <group position={[-1, -5, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_734.geometry}
              material={nodes.Object_734.material}
            />
          </group>
          <group position={[-1, -7, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_736.geometry}
              material={nodes.Object_736.material}
            />
          </group>
          <group position={[1, -7, -1]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_738.geometry}
              material={nodes.Object_738.material}
            />
          </group>
          <group position={[1, -5, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_740.geometry}
              material={nodes.Object_740.material}
            />
          </group>
          <group position={[-1, -5, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_744.geometry}
              material={nodes.Object_744.material}
            />
          </group>
          <group position={[-1, -7, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_746.geometry}
              material={nodes.Object_746.material}
            />
          </group>
          <group position={[1, -7, -3]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_748.geometry}
              material={nodes.Object_748.material}
            />
          </group>
          <group position={[1, -5, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_750.geometry}
              material={nodes.Object_750.material}
            />
          </group>
          <group position={[-1, -5, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_754.geometry}
              material={nodes.Object_754.material}
            />
          </group>
          <group position={[-1, -7, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_756.geometry}
              material={nodes.Object_756.material}
            />
          </group>
          <group position={[1, -7, -5]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_758.geometry}
              material={nodes.Object_758.material}
            />
          </group>
          <group position={[1, -5, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_760.geometry}
              material={nodes.Object_760.material}
            />
          </group>
          <group position={[-1, -5, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_764.geometry}
              material={nodes.Object_764.material}
            />
          </group>
          <group position={[-1, -7, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_766.geometry}
              material={nodes.Object_766.material}
            />
          </group>
          <group position={[1, -7, -7]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_768.geometry}
              material={nodes.Object_768.material}
            />
          </group>
          <group position={[1, -5, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_770.geometry}
              material={nodes.Object_770.material}
            />
          </group>
          <group position={[-1, -5, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_774.geometry}
              material={nodes.Object_774.material}
            />
          </group>
          <group position={[-1, -7, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_776.geometry}
              material={nodes.Object_776.material}
            />
          </group>
          <group position={[1, -7, -9]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_778.geometry}
              material={nodes.Object_778.material}
            />
          </group>
          <group position={[1, -5, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_780.geometry}
              material={nodes.Object_780.material}
            />
          </group>
          <group position={[-1, -5, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_784.geometry}
              material={nodes.Object_784.material}
            />
          </group>
          <group position={[-1, -7, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_786.geometry}
              material={nodes.Object_786.material}
            />
          </group>
          <group position={[1, -7, -11]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_788.geometry}
              material={nodes.Object_788.material}
            />
          </group>
          <group position={[1, -5, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_790.geometry}
              material={nodes.Object_790.material}
            />
          </group>
          <group position={[-1, -5, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_794.geometry}
              material={nodes.Object_794.material}
            />
          </group>
          <group position={[-1, -7, -15]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_796.geometry}
              material={nodes.Object_796.material}
            />
          </group>
          <group position={[1, -7, -13]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_798.geometry}
              material={nodes.Object_798.material}
            />
          </group>
          <group
            name="Cube398_398"
            position={[1, -5, -15]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_800.geometry}
              material={nodes.Object_800.material}
            />
          </group>
          <group scale={3}>
            <mesh
              geometry={nodes.Object_12.geometry}
              material={nodes.Object_12.material}
            />
          </group>
          <group position={[0, 0, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_22.geometry}
              material={nodes.Object_22.material}
            />
          </group>
          <group position={[0, 0, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_32.geometry}
              material={nodes.Object_32.material}
            />
          </group>
          <group position={[0, 0, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_42.geometry}
              material={nodes.Object_42.material}
            />
          </group>
          <group position={[0, 0, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_52.geometry}
              material={nodes.Object_52.material}
            />
          </group>
          <group position={[0, 0, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_62.geometry}
              material={nodes.Object_62.material}
            />
          </group>
          <group position={[0, 0, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_72.geometry}
              material={nodes.Object_72.material}
            />
          </group>
          <group position={[0, 0, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_82.geometry}
              material={nodes.Object_82.material}
            />
          </group>
          <group scale={3}>
            <mesh
              geometry={nodes.Object_92.geometry}
              material={nodes.Object_92.material}
            />
          </group>
          <group position={[0, 0, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_102.geometry}
              material={nodes.Object_102.material}
            />
          </group>
          <group position={[0, 0, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_112.geometry}
              material={nodes.Object_112.material}
            />
          </group>
          <group position={[0, 0, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_122.geometry}
              material={nodes.Object_122.material}
            />
          </group>
          <group position={[0, 0, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_132.geometry}
              material={nodes.Object_132.material}
            />
          </group>
          <group position={[0, 0, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_142.geometry}
              material={nodes.Object_142.material}
            />
          </group>
          <group position={[0, 0, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_152.geometry}
              material={nodes.Object_152.material}
            />
          </group>
          <group position={[0, 0, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_162.geometry}
              material={nodes.Object_162.material}
            />
          </group>
          <group position={[0, 6, 0]} scale={3}>
            <mesh
              geometry={nodes.Object_172.geometry}
              material={nodes.Object_172.material}
            />
          </group>
          <group position={[0, 6, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_182.geometry}
              material={nodes.Object_182.material}
            />
          </group>
          <group position={[0, 6, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_192.geometry}
              material={nodes.Object_192.material}
            />
          </group>
          <group position={[0, 6, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_202.geometry}
              material={nodes.Object_202.material}
            />
          </group>
          <group position={[0, 6, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_212.geometry}
              material={nodes.Object_212.material}
            />
          </group>
          <group position={[0, 6, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_222.geometry}
              material={nodes.Object_222.material}
            />
          </group>
          <group position={[0, 6, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_232.geometry}
              material={nodes.Object_232.material}
            />
          </group>
          <group position={[0, 6, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_242.geometry}
              material={nodes.Object_242.material}
            />
          </group>
          <group position={[0, 6, 0]} scale={3}>
            <mesh
              geometry={nodes.Object_252.geometry}
              material={nodes.Object_252.material}
            />
          </group>
          <group position={[0, 6, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_262.geometry}
              material={nodes.Object_262.material}
            />
          </group>
          <group position={[0, 6, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_272.geometry}
              material={nodes.Object_272.material}
            />
          </group>
          <group position={[0, 6, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_282.geometry}
              material={nodes.Object_282.material}
            />
          </group>
          <group position={[0, 6, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_292.geometry}
              material={nodes.Object_292.material}
            />
          </group>
          <group position={[0, 6, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_302.geometry}
              material={nodes.Object_302.material}
            />
          </group>
          <group position={[0, 6, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_312.geometry}
              material={nodes.Object_312.material}
            />
          </group>
          <group position={[0, 6, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_322.geometry}
              material={nodes.Object_322.material}
            />
          </group>
          <group position={[-6, 0, 0]} scale={3}>
            <mesh
              geometry={nodes.Object_332.geometry}
              material={nodes.Object_332.material}
            />
          </group>
          <group position={[-6, 0, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_342.geometry}
              material={nodes.Object_342.material}
            />
          </group>
          <group position={[-6, 0, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_352.geometry}
              material={nodes.Object_352.material}
            />
          </group>
          <group position={[-6, 0, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_362.geometry}
              material={nodes.Object_362.material}
            />
          </group>
          <group position={[-6, 0, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_372.geometry}
              material={nodes.Object_372.material}
            />
          </group>
          <group position={[-6, 0, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_382.geometry}
              material={nodes.Object_382.material}
            />
          </group>
          <group position={[-6, 0, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_392.geometry}
              material={nodes.Object_392.material}
            />
          </group>
          <group position={[-6, 0, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_402.geometry}
              material={nodes.Object_402.material}
            />
          </group>
          <group position={[-6, 0, 0]} scale={3}>
            <mesh
              geometry={nodes.Object_412.geometry}
              material={nodes.Object_412.material}
            />
          </group>
          <group position={[-6, 0, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_422.geometry}
              material={nodes.Object_422.material}
            />
          </group>
          <group position={[-6, 0, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_432.geometry}
              material={nodes.Object_432.material}
            />
          </group>
          <group position={[-6, 0, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_442.geometry}
              material={nodes.Object_442.material}
            />
          </group>
          <group position={[-6, 0, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_452.geometry}
              material={nodes.Object_452.material}
            />
          </group>
          <group position={[-6, 0, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_462.geometry}
              material={nodes.Object_462.material}
            />
          </group>
          <group position={[-6, 0, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_472.geometry}
              material={nodes.Object_472.material}
            />
          </group>
          <group position={[-6, 0, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_482.geometry}
              material={nodes.Object_482.material}
            />
          </group>
          <group position={[6.1, 0, 0]} scale={3}>
            <mesh
              geometry={nodes.Object_492.geometry}
              material={nodes.Object_492.material}
            />
          </group>
          <group position={[6.1, 0, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_502.geometry}
              material={nodes.Object_502.material}
            />
          </group>
          <group position={[6.1, 0, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_512.geometry}
              material={nodes.Object_512.material}
            />
          </group>
          <group position={[6.1, 0, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_522.geometry}
              material={nodes.Object_522.material}
            />
          </group>
          <group position={[6.1, 0, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_532.geometry}
              material={nodes.Object_532.material}
            />
          </group>
          <group position={[6.1, 0, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_542.geometry}
              material={nodes.Object_542.material}
            />
          </group>
          <group position={[6.1, 0, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_552.geometry}
              material={nodes.Object_552.material}
            />
          </group>
          <group position={[6.1, 0, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_562.geometry}
              material={nodes.Object_562.material}
            />
          </group>
          <group position={[6.1, 0, 0]} scale={3}>
            <mesh
              geometry={nodes.Object_572.geometry}
              material={nodes.Object_572.material}
            />
          </group>
          <group position={[6.1, 0, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_582.geometry}
              material={nodes.Object_582.material}
            />
          </group>
          <group position={[6.1, 0, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_592.geometry}
              material={nodes.Object_592.material}
            />
          </group>
          <group position={[6.1, 0, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_602.geometry}
              material={nodes.Object_602.material}
            />
          </group>
          <group position={[6.1, 0, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_612.geometry}
              material={nodes.Object_612.material}
            />
          </group>
          <group position={[6.1, 0, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_622.geometry}
              material={nodes.Object_622.material}
            />
          </group>
          <group position={[6.1, 0, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_632.geometry}
              material={nodes.Object_632.material}
            />
          </group>
          <group position={[6.1, 0, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_642.geometry}
              material={nodes.Object_642.material}
            />
          </group>
          <group position={[0, -6, 0]} scale={3}>
            <mesh
              geometry={nodes.Object_652.geometry}
              material={nodes.Object_652.material}
            />
          </group>
          <group position={[0, -6, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_662.geometry}
              material={nodes.Object_662.material}
            />
          </group>
          <group position={[0, -6, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_672.geometry}
              material={nodes.Object_672.material}
            />
          </group>
          <group position={[0, -6, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_682.geometry}
              material={nodes.Object_682.material}
            />
          </group>
          <group position={[0, -6, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_692.geometry}
              material={nodes.Object_692.material}
            />
          </group>
          <group position={[0, -6, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_702.geometry}
              material={nodes.Object_702.material}
            />
          </group>
          <group position={[0, -6, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_712.geometry}
              material={nodes.Object_712.material}
            />
          </group>
          <group position={[0, -6, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_722.geometry}
              material={nodes.Object_722.material}
            />
          </group>
          <group position={[0, -6, 0]} scale={3}>
            <mesh
              geometry={nodes.Object_732.geometry}
              material={nodes.Object_732.material}
            />
          </group>
          <group position={[0, -6, -2]} scale={3}>
            <mesh
              geometry={nodes.Object_742.geometry}
              material={nodes.Object_742.material}
            />
          </group>
          <group position={[0, -6, -4]} scale={3}>
            <mesh
              geometry={nodes.Object_752.geometry}
              material={nodes.Object_752.material}
            />
          </group>
          <group position={[0, -6, -6]} scale={3}>
            <mesh
              geometry={nodes.Object_762.geometry}
              material={nodes.Object_762.material}
            />
          </group>
          <group position={[0, -6, -8]} scale={3}>
            <mesh
              geometry={nodes.Object_772.geometry}
              material={nodes.Object_772.material}
            />
          </group>
          <group position={[0, -6, -10]} scale={3}>
            <mesh
              geometry={nodes.Object_782.geometry}
              material={nodes.Object_782.material}
            />
          </group>
          <group position={[0, -6, -12]} scale={3}>
            <mesh
              geometry={nodes.Object_792.geometry}
              material={nodes.Object_792.material}
            />
          </group>
          <group position={[0, -6, -14]} scale={3}>
            <mesh
              geometry={nodes.Object_802.geometry}
              material={nodes.Object_802.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/cube.gltf");
