/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/kaleidoscopic-perception-leave-camera-alone-8a40abc018d2464d85a7fc9fcb401832
title: Kaleidoscopic Perception (Leave Camera Alone)
*/

import React, { useRef, useEffect } from "react";

import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();

  const { scene, animations } = useGLTF("/gltf/cubes.gltf", true);
  const { actions, mixer } = useAnimations(animations, group);
  useEffect(() => {
    actions.Animation.play();
  }, [mixer]);

  return <primitive ref={group} object={scene} dispose={null} />;
}

useGLTF.preload("/gltf/cubes.gltf");
