/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/kaleidoscopic-perception-leave-camera-alone-8a40abc018d2464d85a7fc9fcb401832
title: Kaleidoscopic Perception (Leave Camera Alone)
*/

import React, { useRef, useEffect, useState } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/gltf/cubes.gltf");
  // const { actions, mixer } = useAnimations(animations, group);
  // useEffect(() => {
  //   actions.Animation.play()

  //   console.log(mixer);
  // },[mixer]);
  const [start] = useState(() => Math.random() * 5000);
  const [mixer] = useState(() => new THREE.AnimationMixer());
  useEffect(
    () => void mixer.clipAction(animations[0], group.current).play(),
    []
  );
  useFrame((state, delta) => {
    // mesh.current.position.y = Math.sin(start + state.clock.elapsedTime) * 5;
    // mesh.current.rotation.x =
    //   Math.PI / 2 + (Math.sin(start + state.clock.elapsedTime) * Math.PI) / 10;
    // mesh.current.rotation.y =
    //   (Math.sin(start + state.clock.elapsedTime) * Math.PI) / 2;
    group.current.rotation.y +=
      Math.sin((delta * 3) / 2) * Math.cos((delta * 3) / 2) * 1.5;
    mixer.update(delta * 0.5);
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[4.94, 0, 0.11]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_5.geometry}
              material={nodes.Object_5.material}
            />
          </group>
          <group
            position={[-4.94, 0, -0.11]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_8.geometry}
              material={nodes.Object_8.material}
            />
          </group>
          <group
            position={[0.11, 0, -4.94]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_11.geometry}
              material={nodes.Object_11.material}
            />
          </group>
          <group
            position={[-0.11, 0, 4.94]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_14.geometry}
              material={nodes.Object_14.material}
            />
          </group>
          <group
            position={[3.57, 0, -3.41]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_17.geometry}
              material={nodes.Object_17.material}
            />
          </group>
          <group
            position={[-3.57, 0, 3.41]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_20.geometry}
              material={nodes.Object_20.material}
            />
          </group>
          <group
            position={[-3.41, 0, -3.57]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_23.geometry}
              material={nodes.Object_23.material}
            />
          </group>
          <group
            position={[3.41, 0, 3.57]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_26.geometry}
              material={nodes.Object_26.material}
            />
          </group>
          <group
            position={[4.61, 0, -1.78]}
            rotation={[0, 0, Math.PI]}
            scale={0.98}
          >
            <mesh
              geometry={nodes.Object_29.geometry}
              material={nodes.Object_29.material}
            />
          </group>
          <group
            position={[-4.61, 0, 1.78]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_32.geometry}
              material={nodes.Object_32.material}
            />
          </group>
          <group
            position={[-1.78, 0, -4.61]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_35.geometry}
              material={nodes.Object_35.material}
            />
          </group>
          <group
            position={[1.78, 0, 4.61]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_38.geometry}
              material={nodes.Object_38.material}
            />
          </group>
          <group
            position={[2, 0, -4.52]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_41.geometry}
              material={nodes.Object_41.material}
            />
          </group>
          <group
            position={[-2, 0, 4.52]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_44.geometry}
              material={nodes.Object_44.material}
            />
          </group>
          <group
            position={[-4.52, 0, -2]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_47.geometry}
              material={nodes.Object_47.material}
            />
          </group>
          <group
            position={[4.52, 0, 2]}
            rotation={[0, 0, Math.PI]}
            scale={[0.98, 0.98, 0.98]}
          >
            <mesh
              geometry={nodes.Object_50.geometry}
              material={nodes.Object_50.material}
            />
          </group>
          <group
            position={[4.34, 1.69, 0.96]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_53.geometry}
              material={nodes.Object_53.material}
            />
          </group>
          <group
            position={[-4.34, 1.69, -0.96]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_56.geometry}
              material={nodes.Object_56.material}
            />
          </group>
          <group
            position={[0.96, 1.69, -4.34]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_59.geometry}
              material={nodes.Object_59.material}
            />
          </group>
          <group
            position={[-0.96, 1.69, 4.34]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_62.geometry}
              material={nodes.Object_62.material}
            />
          </group>
          <group
            position={[3.75, 1.69, -2.39]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_65.geometry}
              material={nodes.Object_65.material}
            />
          </group>
          <group
            position={[-3.75, 1.69, 2.39]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_68.geometry}
              material={nodes.Object_68.material}
            />
          </group>
          <group
            position={[-2.39, 1.69, -3.75]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_71.geometry}
              material={nodes.Object_71.material}
            />
          </group>
          <group
            position={[2.39, 1.69, 3.75]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_74.geometry}
              material={nodes.Object_74.material}
            />
          </group>
          <group
            position={[4.38, 1.69, -0.77]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_77.geometry}
              material={nodes.Object_77.material}
            />
          </group>
          <group
            position={[-4.38, 1.69, 0.77]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_80.geometry}
              material={nodes.Object_80.material}
            />
          </group>
          <group
            position={[-0.77, 1.69, -4.38]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_83.geometry}
              material={nodes.Object_83.material}
            />
          </group>
          <group
            position={[0.77, 1.69, 4.38]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_86.geometry}
              material={nodes.Object_86.material}
            />
          </group>
          <group
            position={[2.55, 1.69, -3.64]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_89.geometry}
              material={nodes.Object_89.material}
            />
          </group>
          <group
            position={[-2.55, 1.69, 3.64]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_92.geometry}
              material={nodes.Object_92.material}
            />
          </group>
          <group
            position={[-3.64, 1.69, -2.55]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_95.geometry}
              material={nodes.Object_95.material}
            />
          </group>
          <group
            position={[3.64, 1.69, 2.55]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_98.geometry}
              material={nodes.Object_98.material}
            />
          </group>
          <group
            position={[3.73, 3.07, 0.09]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_101.geometry}
              material={nodes.Object_101.material}
            />
          </group>
          <group
            position={[-3.73, 3.07, -0.09]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_104.geometry}
              material={nodes.Object_104.material}
            />
          </group>
          <group
            position={[0.09, 3.07, -3.73]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_107.geometry}
              material={nodes.Object_107.material}
            />
          </group>
          <group
            position={[-0.09, 3.07, 3.73]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_110.geometry}
              material={nodes.Object_110.material}
            />
          </group>
          <group
            position={[2.7, 3.07, -2.58]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_113.geometry}
              material={nodes.Object_113.material}
            />
          </group>
          <group
            position={[-2.7, 3.07, 2.58]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_116.geometry}
              material={nodes.Object_116.material}
            />
          </group>
          <group
            position={[-2.58, 3.07, -2.7]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_119.geometry}
              material={nodes.Object_119.material}
            />
          </group>
          <group
            position={[2.58, 3.07, 2.7]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_122.geometry}
              material={nodes.Object_122.material}
            />
          </group>
          <group
            position={[3.48, 3.07, -1.35]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_125.geometry}
              material={nodes.Object_125.material}
            />
          </group>
          <group
            position={[-3.48, 3.07, 1.35]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_128.geometry}
              material={nodes.Object_128.material}
            />
          </group>
          <group
            position={[-1.35, 3.07, -3.48]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_131.geometry}
              material={nodes.Object_131.material}
            />
          </group>
          <group
            position={[1.35, 3.07, 3.48]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_134.geometry}
              material={nodes.Object_134.material}
            />
          </group>
          <group
            position={[1.51, 3.07, -3.41]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_137.geometry}
              material={nodes.Object_137.material}
            />
          </group>
          <group
            position={[-1.51, 3.07, 3.41]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_140.geometry}
              material={nodes.Object_140.material}
            />
          </group>
          <group
            position={[-3.41, 3.07, -1.51]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_143.geometry}
              material={nodes.Object_143.material}
            />
          </group>
          <group
            position={[3.41, 3.07, 1.51]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_146.geometry}
              material={nodes.Object_146.material}
            />
          </group>
          <group
            position={[2.97, 4.04, 0.66]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_149.geometry}
              material={nodes.Object_149.material}
            />
          </group>
          <group
            position={[-2.97, 4.04, -0.66]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_152.geometry}
              material={nodes.Object_152.material}
            />
          </group>
          <group
            position={[0.66, 4.04, -2.97]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_155.geometry}
              material={nodes.Object_155.material}
            />
          </group>
          <group
            position={[-0.66, 4.04, 2.97]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_158.geometry}
              material={nodes.Object_158.material}
            />
          </group>
          <group
            position={[2.56, 4.04, -1.64]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_161.geometry}
              material={nodes.Object_161.material}
            />
          </group>
          <group
            position={[-2.56, 4.04, 1.64]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_164.geometry}
              material={nodes.Object_164.material}
            />
          </group>
          <group
            position={[-1.64, 4.04, -2.56]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_167.geometry}
              material={nodes.Object_167.material}
            />
          </group>
          <group
            position={[1.64, 4.04, 2.56]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_170.geometry}
              material={nodes.Object_170.material}
            />
          </group>
          <group
            position={[3, 4.04, -0.53]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_173.geometry}
              material={nodes.Object_173.material}
            />
          </group>
          <group
            position={[-3, 4.04, 0.53]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_176.geometry}
              material={nodes.Object_176.material}
            />
          </group>
          <group
            position={[-0.53, 4.04, -3]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_179.geometry}
              material={nodes.Object_179.material}
            />
          </group>
          <group
            position={[0.53, 4.04, 3]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_182.geometry}
              material={nodes.Object_182.material}
            />
          </group>
          <group
            position={[1.74, 4.04, -2.49]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_185.geometry}
              material={nodes.Object_185.material}
            />
          </group>
          <group
            position={[-1.74, 4.04, 2.49]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_188.geometry}
              material={nodes.Object_188.material}
            />
          </group>
          <group
            position={[-2.49, 4.04, -1.74]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_191.geometry}
              material={nodes.Object_191.material}
            />
          </group>
          <group
            position={[2.49, 4.04, 1.74]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_194.geometry}
              material={nodes.Object_194.material}
            />
          </group>
          <group
            position={[1.87, 4.7, -1.61]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_197.geometry}
              material={nodes.Object_197.material}
            />
          </group>
          <group
            position={[-1.87, 4.7, 1.61]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_200.geometry}
              material={nodes.Object_200.material}
            />
          </group>
          <group
            position={[-1.61, 4.7, -1.87]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_203.geometry}
              material={nodes.Object_203.material}
            />
          </group>
          <group
            position={[1.61, 4.7, 1.87]}
            rotation={[0, 0, Math.PI]}
            scale={0.49}
          >
            <mesh
              geometry={nodes.Object_206.geometry}
              material={nodes.Object_206.material}
            />
          </group>
          <group
            position={[0.18, 4.7, -2.46]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_209.geometry}
              material={nodes.Object_209.material}
            />
          </group>
          <group
            position={[-0.18, 4.7, 2.46]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_212.geometry}
              material={nodes.Object_212.material}
            />
          </group>
          <group
            position={[-2.46, 4.7, -0.18]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_215.geometry}
              material={nodes.Object_215.material}
            />
          </group>
          <group
            position={[2.46, 4.7, 0.18]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_218.geometry}
              material={nodes.Object_218.material}
            />
          </group>
          <group
            position={[1.12, 4.7, -2.21]}
            rotation={[0, 0, Math.PI]}
            scale={0.49}
          >
            <mesh
              geometry={nodes.Object_221.geometry}
              material={nodes.Object_221.material}
            />
          </group>
          <group
            position={[-1.12, 4.7, 2.21]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_224.geometry}
              material={nodes.Object_224.material}
            />
          </group>
          <group
            position={[-2.21, 4.7, -1.12]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_227.geometry}
              material={nodes.Object_227.material}
            />
          </group>
          <group
            position={[2.21, 4.7, 1.12]}
            rotation={[0, 0, Math.PI]}
            scale={0.49}
          >
            <mesh
              geometry={nodes.Object_230.geometry}
              material={nodes.Object_230.material}
            />
          </group>
          <group
            position={[-0.77, 4.7, -2.35]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_233.geometry}
              material={nodes.Object_233.material}
            />
          </group>
          <group
            position={[0.77, 4.7, 2.35]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_236.geometry}
              material={nodes.Object_236.material}
            />
          </group>
          <group
            position={[-2.35, 4.7, 0.77]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_239.geometry}
              material={nodes.Object_239.material}
            />
          </group>
          <group
            position={[2.35, 4.7, -0.77]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_242.geometry}
              material={nodes.Object_242.material}
            />
          </group>
          <group
            position={[4.34, -1.69, 0.96]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_245.geometry}
              material={nodes.Object_245.material}
            />
          </group>
          <group
            position={[-4.34, -1.69, -0.96]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_248.geometry}
              material={nodes.Object_248.material}
            />
          </group>
          <group
            position={[0.96, -1.69, -4.34]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_251.geometry}
              material={nodes.Object_251.material}
            />
          </group>
          <group
            position={[-0.96, -1.69, 4.34]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_254.geometry}
              material={nodes.Object_254.material}
            />
          </group>
          <group
            position={[3.75, -1.69, -2.39]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_257.geometry}
              material={nodes.Object_257.material}
            />
          </group>
          <group
            position={[-3.75, -1.69, 2.39]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_260.geometry}
              material={nodes.Object_260.material}
            />
          </group>
          <group
            position={[-2.39, -1.69, -3.75]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_263.geometry}
              material={nodes.Object_263.material}
            />
          </group>
          <group
            position={[2.39, -1.69, 3.75]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_266.geometry}
              material={nodes.Object_266.material}
            />
          </group>
          <group
            position={[4.38, -1.69, -0.77]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_269.geometry}
              material={nodes.Object_269.material}
            />
          </group>
          <group
            position={[-4.38, -1.69, 0.77]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_272.geometry}
              material={nodes.Object_272.material}
            />
          </group>
          <group
            position={[-0.77, -1.69, -4.38]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_275.geometry}
              material={nodes.Object_275.material}
            />
          </group>
          <group
            position={[0.77, -1.69, 4.38]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_278.geometry}
              material={nodes.Object_278.material}
            />
          </group>
          <group
            position={[2.55, -1.69, -3.64]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_281.geometry}
              material={nodes.Object_281.material}
            />
          </group>
          <group
            position={[-2.55, -1.69, 3.64]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_284.geometry}
              material={nodes.Object_284.material}
            />
          </group>
          <group
            position={[-3.64, -1.69, -2.55]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_287.geometry}
              material={nodes.Object_287.material}
            />
          </group>
          <group
            position={[3.64, -1.69, 2.55]}
            rotation={[0, 0, Math.PI]}
            scale={[0.88, 0.88, 0.88]}
          >
            <mesh
              geometry={nodes.Object_290.geometry}
              material={nodes.Object_290.material}
            />
          </group>
          <group
            position={[3.73, -3.05, 0.09]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_293.geometry}
              material={nodes.Object_293.material}
            />
          </group>
          <group
            position={[-3.73, -3.05, -0.09]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_296.geometry}
              material={nodes.Object_296.material}
            />
          </group>
          <group
            position={[0.09, -3.05, -3.73]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_299.geometry}
              material={nodes.Object_299.material}
            />
          </group>
          <group
            position={[-0.09, -3.05, 3.73]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_302.geometry}
              material={nodes.Object_302.material}
            />
          </group>
          <group
            position={[2.7, -3.05, -2.58]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_305.geometry}
              material={nodes.Object_305.material}
            />
          </group>
          <group
            position={[-2.7, -3.05, 2.58]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_308.geometry}
              material={nodes.Object_308.material}
            />
          </group>
          <group
            position={[-2.58, -3.05, -2.7]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_311.geometry}
              material={nodes.Object_311.material}
            />
          </group>
          <group
            position={[2.58, -3.05, 2.7]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_314.geometry}
              material={nodes.Object_314.material}
            />
          </group>
          <group
            position={[3.48, -3.05, -1.35]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_317.geometry}
              material={nodes.Object_317.material}
            />
          </group>
          <group
            position={[-3.48, -3.05, 1.35]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_320.geometry}
              material={nodes.Object_320.material}
            />
          </group>
          <group
            position={[-1.35, -3.05, -3.48]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_323.geometry}
              material={nodes.Object_323.material}
            />
          </group>
          <group
            position={[1.35, -3.05, 3.48]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_326.geometry}
              material={nodes.Object_326.material}
            />
          </group>
          <group
            position={[1.51, -3.05, -3.41]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_329.geometry}
              material={nodes.Object_329.material}
            />
          </group>
          <group
            position={[-1.51, -3.05, 3.41]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_332.geometry}
              material={nodes.Object_332.material}
            />
          </group>
          <group
            position={[-3.41, -3.05, -1.51]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_335.geometry}
              material={nodes.Object_335.material}
            />
          </group>
          <group
            position={[3.41, -3.05, 1.51]}
            rotation={[0, 0, Math.PI]}
            scale={[0.74, 0.74, 0.74]}
          >
            <mesh
              geometry={nodes.Object_338.geometry}
              material={nodes.Object_338.material}
            />
          </group>
          <group
            position={[2.97, -3.98, 0.66]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_341.geometry}
              material={nodes.Object_341.material}
            />
          </group>
          <group
            position={[-2.97, -3.98, -0.66]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_344.geometry}
              material={nodes.Object_344.material}
            />
          </group>
          <group
            position={[0.66, -3.98, -2.97]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_347.geometry}
              material={nodes.Object_347.material}
            />
          </group>
          <group
            position={[-0.66, -3.98, 2.97]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_350.geometry}
              material={nodes.Object_350.material}
            />
          </group>
          <group
            position={[2.56, -3.98, -1.64]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_353.geometry}
              material={nodes.Object_353.material}
            />
          </group>
          <group
            position={[-2.56, -3.98, 1.64]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_356.geometry}
              material={nodes.Object_356.material}
            />
          </group>
          <group
            position={[-1.64, -3.98, -2.56]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_359.geometry}
              material={nodes.Object_359.material}
            />
          </group>
          <group
            position={[1.64, -3.98, 2.56]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_362.geometry}
              material={nodes.Object_362.material}
            />
          </group>
          <group
            position={[3, -3.98, -0.53]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_365.geometry}
              material={nodes.Object_365.material}
            />
          </group>
          <group
            position={[-3, -3.98, 0.53]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_368.geometry}
              material={nodes.Object_368.material}
            />
          </group>
          <group
            position={[-0.53, -3.98, -3]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_371.geometry}
              material={nodes.Object_371.material}
            />
          </group>
          <group
            position={[0.53, -3.98, 3]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_374.geometry}
              material={nodes.Object_374.material}
            />
          </group>
          <group
            position={[1.74, -3.98, -2.49]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_377.geometry}
              material={nodes.Object_377.material}
            />
          </group>
          <group
            position={[-1.74, -3.98, 2.49]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_380.geometry}
              material={nodes.Object_380.material}
            />
          </group>
          <group
            position={[-2.49, -3.98, -1.74]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_383.geometry}
              material={nodes.Object_383.material}
            />
          </group>
          <group
            position={[2.49, -3.98, 1.74]}
            rotation={[0, 0, Math.PI]}
            scale={[0.6, 0.6, 0.6]}
          >
            <mesh
              geometry={nodes.Object_386.geometry}
              material={nodes.Object_386.material}
            />
          </group>
          <group
            position={[2.47, -4.68, 0.06]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_389.geometry}
              material={nodes.Object_389.material}
            />
          </group>
          <group
            position={[-2.47, -4.68, -0.06]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_392.geometry}
              material={nodes.Object_392.material}
            />
          </group>
          <group
            position={[0.06, -4.68, -2.47]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_395.geometry}
              material={nodes.Object_395.material}
            />
          </group>
          <group
            position={[-0.06, -4.68, 2.47]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_398.geometry}
              material={nodes.Object_398.material}
            />
          </group>
          <group
            position={[1.79, -4.68, -1.71]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_401.geometry}
              material={nodes.Object_401.material}
            />
          </group>
          <group
            position={[-1.79, -4.68, 1.71]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_404.geometry}
              material={nodes.Object_404.material}
            />
          </group>
          <group
            position={[-1.71, -4.68, -1.79]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_407.geometry}
              material={nodes.Object_407.material}
            />
          </group>
          <group
            position={[1.71, -4.68, 1.79]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_410.geometry}
              material={nodes.Object_410.material}
            />
          </group>
          <group
            position={[2.31, -4.68, -0.89]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_413.geometry}
              material={nodes.Object_413.material}
            />
          </group>
          <group
            position={[-2.31, -4.68, 0.89]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_416.geometry}
              material={nodes.Object_416.material}
            />
          </group>
          <group
            position={[-0.89, -4.68, -2.31]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_419.geometry}
              material={nodes.Object_419.material}
            />
          </group>
          <group
            position={[0.89, -4.68, 2.31]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_422.geometry}
              material={nodes.Object_422.material}
            />
          </group>
          <group
            position={[1, -4.68, -2.26]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_425.geometry}
              material={nodes.Object_425.material}
            />
          </group>
          <group
            position={[-1, -4.68, 2.26]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_428.geometry}
              material={nodes.Object_428.material}
            />
          </group>
          <group
            position={[-2.26, -4.68, -1]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_431.geometry}
              material={nodes.Object_431.material}
            />
          </group>
          <group
            position={[2.26, -4.68, 1]}
            rotation={[0, 0, Math.PI]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.Object_434.geometry}
              material={nodes.Object_434.material}
            />
          </group>
          <group
            name="Sphere_288"
            position={[0, -6, 0]}
            rotation={[0, -0.02, 0]}
            scale={1.6}
          >
            <mesh
              geometry={nodes.Object_436.geometry}
              material={materials.material_1}
            />
          </group>
          <group rotation={[0, 0.2, 0]} scale={8.2}>
            <mesh
              geometry={nodes.Object_439.geometry}
              material={materials.hide}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/gltf/cubes.gltf");
