/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ethereal-diodes-33d1046cbb654655b9689bbcbedf24d4
title: Ethereal Diodes
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const texture = useTexture("/textures/diodes.png");

  const { scene, nodes, materials, animations } = useGLTF("/gltf/diodes.gltf");
  const { actions, ref, clip, mixer } = useAnimations(animations, group);
  useEffect(() => {
    // console.log(animations, actions, ref, clip, mixer);
    // actions.animation
    actions.Animation.play();
    // animations.forEach((clip) => {
    //   // const action = mixer.clipAction(clip);
    //   // clip.play()
    //   // action.play();
    //   console.log(clip)
    // });
  });
  // useFrame((state, delta) => {
  //   // mixer?.update(delta);
  // });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.97, 0, -0.12]}>
            <mesh
              geometry={nodes.Object_6.geometry}
              material={nodes.Object_6.material}
            />
            <mesh
              geometry={nodes.Object_4.geometry}
              material={nodes.Object_4.material}
            />
          </group>
          <group position={[-0.85, 0.03, -0.13]}>
            <mesh
              geometry={nodes.Object_12.geometry}
              material={nodes.Object_12.material}
            />
            <mesh
              geometry={nodes.Object_10.geometry}
              material={nodes.Object_10.material}
            />
          </group>
          <group position={[0.02, 0.18, 0.91]}>
            <mesh
              geometry={nodes.Object_16.geometry}
              material={nodes.Object_16.material}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={nodes.Object_14.material}
            />
          </group>
          <group name="Helix006_8" position={[0.07, 0.18, -1.09]}>
            <mesh
              geometry={nodes.Object_20.geometry}
              material={nodes.Object_20.material}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={nodes.Object_18.material}
            />
          </group>
          <group position={[0, 1.47, 0]} scale={[0.4, 1.52, 0.4]}>
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.hide}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/diodes.gltf");
