/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: pinguinoconpulgares (https://sketchfab.com/pinguinoconpulgares)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/aab50e87032648dba2d25be49be8563e
title: Explorer
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/gltf/explorer.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[-0.31, -0.43, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <primitive object={nodes.Armature003_rootJoint} />
        </group>
        <group position={[0.01, 0, 0.16]} scale={4.81}>
          <mesh
            geometry={nodes.Plane001_0.geometry}
            material={materials.ROCK}
          />
          <mesh
            geometry={nodes.Plane001_1.geometry}
            material={materials.Material}
          ></mesh>
          <mesh
            geometry={nodes.Plane001_2.geometry}
            material={materials.floor}
          />
          <mesh
            geometry={nodes.Plane001_3.geometry}
            material={materials.HELMROCK}
          />
          <mesh
            geometry={nodes.Plane001_4.geometry}
            material={materials["EYES.001"]}
          />
          <mesh
            geometry={nodes.Plane001_5.geometry}
            material={materials.SWORD}
          />
        </group>
        <group position={[-0.2, 1.47, 0.24]} scale={0.29}>
          <mesh geometry={nodes.Cube000_0.geometry} material={materials.spires}>
            <meshLambertMaterial reflectivity={3}/>
          </mesh>
        </group>
        <group
          position={[1.74, -0.43, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <primitive object={nodes.Armature004_rootJoint} />
        </group>
        <group
          position={[-2.31, -0.43, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <primitive object={nodes.Armature005_rootJoint} />
        </group>
        <group
          position={[-2.54, -1.22, 0.4]}
          rotation={[-1.54, 1.33, -3.12]}
          scale={[0.01, 0.01, 0.01]}
        >
          <primitive object={nodes.Armature007_rootJoint} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/gltf/explorer.gltf");
