/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nurfaamk Cyform (https://sketchfab.com/nurhudaiffah)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bloom-light-and-mountain-997bf480e6a64ac0bb6c8109bd38543f
title: BLOOM LIGHT AND MOUNTAIN
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gltf/lightmountain.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-40.56, 51.85, 0]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube13_lambert3_0.geometry} material={nodes.pCube13_lambert3_0.material} />
          </group>
          <group position={[-40.56, 155.4, 0]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube12_lambert3_0.geometry} material={nodes.pCube12_lambert3_0.material} />
          </group>
          <group position={[-23.23, 93.1, 71.27]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube11_lambert3_0.geometry} material={nodes.pCube11_lambert3_0.material} />
          </group>
          <group position={[-62.43, 93.1, 71.27]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube10_lambert3_0.geometry} material={nodes.pCube10_lambert3_0.material} />
          </group>
          <group position={[-62.43, 93.1, -72.65]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube9_lambert3_0.geometry} material={nodes.pCube9_lambert3_0.material} />
          </group>
          <group position={[-23.23, 93.1, -72.65]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube8_lambert3_0.geometry} material={nodes.pCube8_lambert3_0.material} />
          </group>
          <group position={[0, -9.9, 0]} scale={1188.28}>
            <mesh geometry={nodes.pPlane1_lambert2_0.geometry} material={materials.lambert2} />
          </group>
          <group position={[-73.94, 93.1, -106.25]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube6_lambert3_0.geometry} material={nodes.pCube6_lambert3_0.material} />
          </group>
          <group position={[0, 93.1, -106.25]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube7_lambert3_0.geometry} material={nodes.pCube7_lambert3_0.material} />
          </group>
          <group position={[-39.2, 93.1, -106.25]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube5_lambert3_0.geometry} material={nodes.pCube5_lambert3_0.material} />
          </group>
          <group position={[-39.2, 93.1, 105.24]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube4_lambert3_0.geometry} material={nodes.pCube4_lambert3_0.material} />
          </group>
          <group position={[-40.56, 105.14, 0]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube1_lambert3_0.geometry} material={nodes.pCube1_lambert3_0.material} />
          </group>
          <group position={[-73.94, 93.1, 105.24]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube3_lambert3_0.geometry} material={nodes.pCube3_lambert3_0.material} />
          </group>
          <group position={[0, 93.1, 105.24]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube2_lambert3_0.geometry} material={nodes.pCube2_lambert3_0.material} />
          </group>
          <group position={[-236.2, 93.1, 71.27]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube14_lambert3_0.geometry} material={nodes.pCube14_lambert3_0.material} />
          </group>
          <group position={[-197, 93.1, 71.27]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube15_lambert3_0.geometry} material={nodes.pCube15_lambert3_0.material} />
          </group>
          <group position={[-212.97, 93.1, -106.25]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube16_lambert3_0.geometry} material={nodes.pCube16_lambert3_0.material} />
          </group>
          <group position={[-173.77, 93.1, -106.25]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube17_lambert3_0.geometry} material={nodes.pCube17_lambert3_0.material} />
          </group>
          <group position={[-197, 93.1, -72.65]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube18_lambert3_0.geometry} material={nodes.pCube18_lambert3_0.material} />
          </group>
          <group position={[-247.71, 93.1, -106.25]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube19_lambert3_0.geometry} material={nodes.pCube19_lambert3_0.material} />
          </group>
          <group position={[-236.2, 93.1, -72.65]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube20_lambert3_0.geometry} material={nodes.pCube20_lambert3_0.material} />
          </group>
          <group position={[-173.77, 93.1, 105.24]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube21_lambert3_0.geometry} material={nodes.pCube21_lambert3_0.material} />
          </group>
          <group position={[-247.71, 93.1, 105.24]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube22_lambert3_0.geometry} material={nodes.pCube22_lambert3_0.material} />
          </group>
          <group position={[-212.97, 93.1, 105.24]} scale={[0.92, 38.77, 0.92]}>
            <mesh geometry={nodes.pCube23_lambert3_0.geometry} material={nodes.pCube23_lambert3_0.material} />
          </group>
          <group position={[67.73, -24.98, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={437.27}>
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_1.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_1.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_2.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_2.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_3.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_3.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_4.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_4.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_5.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_5.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_6.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_6.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_7.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_7.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_8.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_8.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_9.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_9.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_10.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_10.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_11.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_11.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_12.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_12.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_13.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_13.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_14.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_14.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_15.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_15.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_16.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_16.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_17.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_17.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_18.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_18.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_19.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_19.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_20.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_20.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_21.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_21.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_22.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_22.material}
            />
            <mesh
              geometry={nodes.Striking_MountainsTerrainMesh_lambert1_0_23.geometry}
              material={nodes.Striking_MountainsTerrainMesh_lambert1_0_23.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gltf/lightmountain.gltf')
