/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Dmitry Shayakhmetov (https://sketchfab.com/dmitryshayakhmetov)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spaceman-b28781d2ffce407c8f508fb73232bee9
title: SpaceMan
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gltf/spaceman.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.07, -0.59, -2.6]} rotation={[-2.64, -0.06, 0.17]} scale={[0.08, 0.08, 0.08]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['tiger-edit']} />
          </group>
          <group position={[-0.08, -0.43, -0.84]} rotation={[3.01, -0.02, 2.98]} scale={[0.63, 0.63, 0.63]}>
            <mesh geometry={nodes.Object_9.geometry} material={materials['1sTONEnEW']} />
          </group>
          <group position={[0.08, -0.51, -2.64]} rotation={[-0.14, -0.62, -0.06]} scale={[0, 0, 0]}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.material_3} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.material_4} />
          </group>
          <group position={[-0.01, 0.19, -1.03]} rotation={[0, 1.04, -Math.PI / 2]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
          </group>
          <group position={[-0.07, -0.41, -0.92]} rotation={[0, -0.53, 0]} scale={0.13}>
            <mesh geometry={nodes.Object_24.geometry} material={materials['Boti.001']} />
            <mesh geometry={nodes.Object_28.geometry} material={materials['Lamki.001']} />
            <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
            <mesh geometry={nodes.Object_35.geometry} material={materials['Bag.001']} />
            <mesh geometry={nodes.Object_39.geometry} material={materials['Cloth.001']} />
            <mesh geometry={nodes.Object_42.geometry} material={materials['Cloth2.001']} />
            <mesh geometry={nodes.Object_45.geometry} material={nodes.Object_45.material} />
            <mesh geometry={nodes.Object_49.geometry} material={materials['Man.001']} />
            <mesh geometry={nodes.Object_53.geometry} material={materials.Glass2} />
            <mesh geometry={nodes.Object_57.geometry} material={materials['Osheinik.001']} />
          </group>
          <group position={[-3.21, -0.13, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.16, 0.65, 0.16]}>
            <mesh geometry={nodes.Object_60.geometry} material={nodes.Object_60.material} />
            <mesh geometry={nodes.Object_62.geometry} material={nodes.Object_62.material} />
            <mesh geometry={nodes.Object_64.geometry} material={nodes.Object_64.material} />
          </group>
          <group position={[0.14, -0.09, -0.03]} rotation={[1.82, -0.43, 2.36]} scale={[5.02, 5.02, 5.02]}>
            <mesh geometry={nodes.Object_67.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0.02, -0.1, 0.07]} rotation={[3.12, 0.02, 0.29]} scale={[-0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.Object_70.geometry} material={materials.None} />
            <mesh geometry={nodes.Object_72.geometry} material={materials.SaturnRings} />
          </group>
          <group position={[-3.21, -0.13, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.16, 0.65, 0.16]}>
            <mesh geometry={nodes.Object_75.geometry} material={nodes.Object_75.material} />
            <mesh geometry={nodes.Object_77.geometry} material={nodes.Object_77.material} />
            <mesh geometry={nodes.Object_79.geometry} material={nodes.Object_79.material} />
          </group>
          <group position={[-3.19, -0.14, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.04, 1.99, 0.04]}>
            <mesh geometry={nodes.Object_82.geometry} material={nodes.Object_82.material} />
          </group>
          <group position={[-3.19, -0.14, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.04, 1.99, 0.04]}>
            <mesh geometry={nodes.Object_85.geometry} material={nodes.Object_85.material} />
          </group>
          <mesh geometry={nodes.Object_88.geometry} material={materials.Mount} />
          <group position={[-0.49, -0.46, 1.4]} rotation={[-0.11, -0.09, -0.06]} scale={[0.54, 0.54, 0.54]}>
            <mesh geometry={nodes.Object_91.geometry} material={materials.Trava} />
          </group>
          <group position={[-0.74, -0.36, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={[0.15, 0.28, 0.2]}>
            <mesh geometry={nodes.Object_94.geometry} material={materials.Fire} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gltf/spaceman.gltf')
